# ============================================
# Patient Service - Môi trường PROD (PostgreSQL)
# ============================================
server.port=8082
spring.application.name=patient-service

# Cấu hình PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/patient_db_prod
spring.datasource.username=postgres
spring.datasource.password=f540b751852ef301706dda3cad4b2d2fff28c8bdd5a65ec0db9ac5e34c8be446
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging (prod: chỉ log warning/error)
logging.level.com.example.patientservice=WARN
logging.level.org.hibernate.SQL=WARN