# ============================================
# Patient Service - Môi trường DEV (MySQL)
# ============================================
server.port=8081
spring.application.name=patient-service

# Cấu hình MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/patient_db_dev?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=f540b751852ef301706dda3cad4b2d2fff28c8bdd5a65ec0db9ac5e34c8be446
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.com.example.patientservice=DEBUG
logging.level.org.hibernate.SQL=DEBUG

app.welcome=Chào mừng tới BV RikkeiAcademy