spring.datasource.url=jdbc:postgresql://localhost:5432/md4_s7
spring.datasource.username=postgres
spring.datasource.password=f540b751852ef301706dda3cad4b2d2fff28c8bdd5a65ec0db9ac5e34c8be446
spring.jpa.hibernate.ddl-auto=update